language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage
  - python setup.py -q install
branches:
 only:
  - master
  - develop
  - /^feature\/.+/
  - /^release\/.+/
  - /^hotfix\/.+/
  - /^v[\d\.]+/
script: coverage run --source=envconf --omit="envconf/schemas/*.py" setup.py test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
    - python: "2.6"
      env: DJANGO_VERSION=1.9
    - python: "2.6"
      env: DJANGO_VERSION=1.10
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.5
    - python: "3.4"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.5
    - python: "3.5"
      env: DJANGO_VERSION=1.4
    - python: "3.5"
      env: DJANGO_VERSION=1.5
after_success:
  - pip install python-coveralls
  - coveralls
